# Generated by Django 6.0.2 on 2026-04-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('caixa', 'Caixa'), ('atendente', 'Atendente'), ('padeiro', 'Padeiro')], max_length=20)),
                ('turno', models.CharField(choices=[('manha', 'Manha'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=10)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
