# Generated by Django 6.0.2 on 2026-04-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
