# Generated by Django 6.0.2 on 2026-04-09 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('rg', 'RG'), ('cpf', 'CPF'), ('exame', 'Exame Medico'), ('curriculo', 'Curriculo'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
