# Generated by Django 6.0.2 on 2026-03-15 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo_preco',
            field=models.CharField(choices=[('unidade', 'Por Unidade'), ('kg', 'Por Kg')], default='unidade', max_length=10, verbose_name='Tipo de Preco'),
        ),
    ]
