# Generated by Django 6.0.2 on 2026-05-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observacao'),
        ),
    ]
